### Exbir todos os perfis
GET http://localhost:3333/perfil
Content-type: application/json

### Exbir perfil unico
GET http://localhost:3333/perfil/1
Content-type: application/json

### Exbir todos os perfis ativos
GET http://localhost:3333/perfilAtivo
Content-type: application/json

### Criar um perfil
POST http://localhost:3333/perfil
Content-type: application/json

{
    "nome": "Analista",
    "descricao": "Usuário com permissões de analistas"
}


### Editar um perfil
PUT http://localhost:3333/perfil/1
Content-type: application/json

{
    "nome": "Administrador",
    "descricao": "Usuário com permissões de administrador",
    "ativo": true
}


### Deletar um perfil
DELETE  http://localhost:3333/perfil/2